export const SECRETS: string[] = [
	`After Tuesday, even the calendar says WTF.`,
	`I tried to be normal once... worst two minutes of my entire life.`,
	`I like to be an example for others. Usually a bad example, though.`,
	`Common sense is like deodorant... the people who need it most never seem to use it.`,
	`I'd like to help you out today, which way did you come in?`,
	`If you can't laugh at yourself, I can help you out.`,
	`Every woman should marry an archeologist. Because the older she gets, the more he'll love her.`,
	`Everyone talks about the early bird's good luck, but what about the early worm's bad luck?`,
	`Pobody's nerfect!`,
	`People are like refrigerators: it's what's inside that matters.`,
	`Excuse my naivety... I was born at a very early age.`,
	`Take my advice... I'm not using it.`,
	`I used to think I was indecisive, but now I'm not really sure.`,
	`Try this: Call your friend and let them know you can't talk right now.`,
	`I respect the opinion of everyone who agrees with me.`,
	`I'm not always hungry; sometimes I'm sleepy, too.`,
	`Patience is a virtue, but I don't want to wait.`,
	`I'm out of my mind... be back in five minutes!`,
	`When everything in life is coming your way, you're probably in the wrong lane.`,
	`If you want to look thin and young, hang out with some fat old people.`,
	`My parents moved around a lot when I was growing up, but I always found them.`,
	`Try this: Walk to the line for the nearest public bathroom and ask, "So, they fixed this one? Thank God! I just changed into some dry clothes."`,
	`I've always thought air was free. That is, I did until I went out and bought a $3 bag of chips.`,
	`Try this: Before you leave a room, say, "I bid you farewell!`,
	`Try this: When you shake someone's hand, jokingly say, "I'm so glad you had the privilege of meeting me".`,
	`Love must truly be blind because it can't see me at all.`,
	`The problem was he/she wanted a serious relationship, and I'm a funny girl/guy.`,
	`If plan A fails, at least there are 25 more letters in the alphabet.`,
	`An apple a day keeps the doctor away... if you throw it hard enough!`,
	`Beauty is in the eye of the beer holder.`,
	`I'm super excited for the new year. Unfortunately, I don't have any resolutions to make since I'm already perfect.`,
	`It's not that I totally trust you, I'm just feeling lazy today.`,
	`I try to have an open mind, but my brain keeps falling out.`,
	`There're many pessimists who got that way by investing in an optimist.`,
]
