name: CI

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Deps
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint:ci
      
      - name: Build
        run: |
          npm run build

      - name: Tests
        run: |
          npm run test
